<?php
array(
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("Hide first (hours) column", "timetable"),
		"param_name" => "hide_hours_column",
		"value" => array(
			__("No", "timetable") => "0",
			__("Yes", "timetable") => "1",
		),
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("Show end hour in first (hours) column", "timetable"),
		"param_name" => "show_end_hour",
		"value" => array(
			__("No", "timetable") => "0",
			__("Yes", "timetable") => "1",
		),
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("Event block layout", "timetable"),
		"param_name" => "event_layout",
		"value" => array(
			__("Type 1", "timetable") => "1",
			__("Type 2", "timetable") => "2",
			__("Type 3", "timetable") => "3",
			__("Type 4", "timetable") => "4",
			__("Type 5", "timetable") => "5",
		),
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("Hide empty rows", "timetable"),
		"param_name" => "hide_empty",
		"value" => array(
			__("No", "timetable") => "0",
			__("Yes", "timetable") => "1",
		),
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("Disable event url", "timetable"),
		"param_name" => "disable_event_url",
		"value" => array(
			__("No", "timetable") => "0",
			__("Yes", "timetable") => "1",
		),
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("Text align", "timetable"),
		"param_name" => "text_align",
		"value" => array(
			__("center", "timetable") => "center",
			__("left", "timetable") => "left",
			__("right", "timetable") => "right",
		),
	),
	array(
		"type" => "textfield",
		"class" => "",
		"heading" => __("Id", "timetable"),
		"param_name" => "id",
		"value" => "",
	),
	array(
		"type" => "textfield",
		"class" => "",
		"heading" => __("Row height (in px)", "timetable"),
		"param_name" => "row_height",
		"value" => "31",
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("Display list view on desktop", "timetable"),
		"param_name" => "desktop_list_view",
		"value" => array(
			__("No", "timetable") => "0",
			__("Yes", "timetable") => "1",
		),
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("Responsive", "timetable"),
		"param_name" => "responsive",
		"value" => array(
			__("Yes", "timetable") => "1",
			__("No", "timetable") => "0",
		),
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("Event description in responsive mode", "timetable"),
		"param_name" => "event_description_responsive",
		"value" => array(
			__("None", "timetable") => "none",
			__("Only Description 1", "timetable") => "description-1",
			__("Only Description 2", "timetable") => "description-2",
			__("Description 1 and Description 2", "timetable") => "description-1-and-description-2",
		),
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("Collapse event hours in responsive mode", "timetable"),
		"param_name" => "collapse_event_hours_responsive",
		"value" => array(
			__("No", "timetable") => "0",
			__("Yes", "timetable") => "1",
		),
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("Use colors in responsive mode", "timetable"),
		"param_name" => "colors_responsive_mode",
		"value" => array(
			__("No", "timetable") => "0",
			__("Yes", "timetable") => "1",
		),
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("Export to PDF button", "timetable"),
		"param_name" => "export_to_pdf_button",
		"value" => array(
			__("No", "timetable") => "0",
			__("Yes", "timetable") => "1",
		),
	),
	array(
		"type" => "textfield",
		"class" => "",
		"heading" => __("Generate PDF label", "timetable"),
		"param_name" => "generate_pdf_label",
		"value" => __("Generate PDF", "timetable"),
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("PDF Font", "timetable"),
		"param_name" => "pdf_font",
		"value" => array(
			__("Lato", "timetable") => "lato",
			__("DejaVu Sans", "timetable") => "dejavusans",
		),
	),
	array(
		"type" => "colorpicker",
		"class" => "",
		"heading" => __("Timetable box background color", "timetable"),
		"param_name" => "box_bg_color",
		"value" => "#00a27c",
	),
	array(
		"type" => "colorpicker",
		"class" => "",
		"heading" => __("Timetable box hover background color", "timetable"),
		"param_name" => "box_hover_bg_color",
		"value" => "#1f736a",
	),
	array(
		"type" => "colorpicker",
		"class" => "",
		"heading" => __("Timetable box text color", "timetable"),
		"param_name" => "box_txt_color",
		"value" => "#ffffff",
	),
	array(
		"type" => "colorpicker",
		"class" => "",
		"heading" => __("Timetable box hover text color", "timetable"),
		"param_name" => "box_hover_txt_color",
		"value" => "#ffffff",
	),
	array(
		"type" => "colorpicker",
		"class" => "",
		"heading" => __("Timetable box hours text color", "timetable"),
		"param_name" => "box_hours_txt_color",
		"value" => "#ffffff",
	),
	array(
		"type" => "colorpicker",
		"class" => "",
		"heading" => __("Timetable box hours hover text color", "timetable"),
		"param_name" => "box_hours_hover_txt_color",
		"value" => "#ffffff",
	),
	array(
		"type" => "colorpicker",
		"class" => "",
		"heading" => __("Filter control background color", "timetable"),
		"param_name" => "filter_color",
		"value" => "#00a27c",
	),
	array(
		"type" => "colorpicker",
		"class" => "",
		"heading" => __("Row 1 style background color", "timetable"),
		"param_name" => "row1_color",
		"value" => "#f0f0f0",
	),
	array(
		"type" => "colorpicker",
		"class" => "",
		"heading" => __("Row 2 style background color", "timetable"),
		"param_name" => "row2_color",
		"value" => "",
	),
	array(
		"type" => "colorpicker",
		"class" => "",
		"heading" => __("Generate PDF button text color", "timetable"),
		"param_name" => "generate_pdf_text_color",
		"value" => "#ffffff",
	),
	array(
		"type" => "colorpicker",
		"class" => "",
		"heading" => __("Generate PDF button background color", "timetable"),
		"param_name" => "generate_pdf_bg_color",
		"value" => "#00a27c",
	),
	array(
		"type" => "colorpicker",
		"class" => "",
		"heading" => __("Generate PDF button hover text color", "timetable"),
		"param_name" => "generate_pdf_hover_text_color",
		"value" => "#ffffff",
	),
	array(
		"type" => "colorpicker",
		"class" => "",
		"heading" => __("Generate PDF button hover background color", "timetable"),
		"param_name" => "generate_pdf_hover_bg_color",
		"value" => "#1f736a",
	),
	array(
		"type" => "colorpicker",
		"class" => "",
		"heading" => __("Booking button text color", "timetable"),
		"param_name" => "booking_text_color",
		"value" => "#ffffff",
	),
	array(
		"type" => "colorpicker",
		"class" => "",
		"heading" => __("Booking button background color", "timetable"),
		"param_name" => "booking_bg_color",
		"value" => "#05bb90",
	),
	array(
		"type" => "colorpicker",
		"class" => "",
		"heading" => __("Booking button hover text color", "timetable"),
		"param_name" => "booking_hover_text_color",
		"value" => "#ffffff",
	),
	array(
		"type" => "colorpicker",
		"class" => "",
		"heading" => __("Booking button hover background color", "timetable"),
		"param_name" => "booking_hover_bg_color",
		"value" => "#07b38a",
	),
	array(
		"type" => "colorpicker",
		"class" => "",
		"heading" => __("Booked button text color", "timetable"),
		"param_name" => "booked_text_color",
		"value" => "#aaaaaa",
	),
	array(
		"type" => "colorpicker",
		"class" => "",
		"heading" => __("Booked button background color", "timetable"),
		"param_name" => "booked_bg_color",
		"value" => "#eeeeee",
	),
	array(
		"type" => "colorpicker",
		"class" => "",
		"heading" => __("Unavailable button text color", "timetable"),
		"param_name" => "unavailable_text_color",
		"value" => "#aaaaaa",
	),
	array(
		"type" => "colorpicker",
		"class" => "",
		"heading" => __("Unavailable button background color", "timetable"),
		"param_name" => "unavailable_bg_color",
		"value" => "#eeeeee",
	),
	array(
		"type" => "colorpicker",
		"class" => "",
		"heading" => __("Available slots color", "timetable"),
		"param_name" => "available_slots_color",
		"value" => "#ffd544",
	),
	array(
		"type" => "textfield",
		"class" => "",
		"heading" => __("Table header font", "timetable"),
		"param_name" => "font_custom",
		"value" => "",
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("or choose Google font", "timetable"),
		"param_name" => "font",
		"value" => $google_fonts_array,
	),
	array(
		"type" => "dropdownmulti",
		"class" => "",
		"heading" => __("Google font subset", "timetable"),
		"param_name" => "font_subset",
		"value" => array(
			"",
			"arabic",
			"hebrew",
			"telugu",
			"cyrillic-ext",
			"cyrillic",
			"devanagari",
			"greek-ext",
			"greek",
			"vietnamese",
			"latin-ext",
			"latin",
			"khmer",
		),
		"dependency" => array(
			"element" => "font",
			"not_empty" => true,
			"callback" => "timetable_font_subset_init",
		),
	),
	array(
		"type" => "textfield",
		"class" => "",
		"heading" => __("Font size (in px)", "timetable"),
		"param_name" => "font_size",
		"value" => "",
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("Show booking button", "timetable"),
		"param_name" => "show_booking_button",
		"value" => array(
			__("No", "timetable") => "no",
			__("Always", "timetable") => "always",
			__("On hover", "timetable") => "on_hover",
		),
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("Show available slots", "timetable"),
		"param_name" => "show_available_slots",
		"value" => array(
			__("No", "timetable") => "no",
			__("Always", "timetable") => "always",
		),
	),
	array(
		"type" => "textfield",
		"class" => "",
		"heading" => __("Available slots singular label", "timetable"),
		"param_name" => "available_slots_singular_label",
		"value" => "{number_available}/{number_total} slot available",
		"description" => __("Specify text label for 'slot available' information (singular). Available placeholders: {number_available}, {number_taken}, {number_total}.", "timetable")
	),
	array(
		"type" => "textfield",
		"class" => "",
		"heading" => __("Available slots plural label", "timetable"),
		"param_name" => "available_slots_plural_label",
		"value" => "{number_available}/{number_total} slots available",
		"description" => __("Specify text label for 'slots available' information (plural). Available placeholders: {number_available}, {number_taken}, {number_total}.", "timetable")
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("Default booking view", "timetable"),
		"param_name" => "default_booking_view",
		"value" => array(
			__("User", "timetable") => "user",
			__("Guest", "timetable") => "guest",
		),
		"description" => __("Specify which booking view should be visible by default.", "timetable"),
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("Allow user booking", "timetable"),
		"param_name" => "allow_user_booking",
		"value" => array(
			__("Yes", "timetable") => "yes",
			__("No", "timetable") => "no",
		),
		"description" => __("Set to 'Yes' if you want to allow logged in users to make a booking.", "timetable"),
		"dependency" => array(
			"element" => "default_booking_view",
			"value" => array("guest"),
		),
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("Allow guest booking", "timetable"),
		"param_name" => "allow_guest_booking",
		"value" => array(
			__("No", "timetable") => "no",
			__("Yes", "timetable") => "yes",
		),
		"description" => __("Set to 'Yes' if you want to allow guests to make a booking.", "timetable"),
		/*"dependency" => array(
			"element" => "default_booking_view",
			"value" => array("user"),
		),*/
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("Show guest name field", "timetable"),
		"param_name" => "show_guest_name_field",
		"value" => array(
			__("Yes", "timetable") => "yes",
			__("No", "timetable") => "no",
		),
		"dependency" => array(
			"element" => "allow_guest_booking",
			"value" => array("yes"),
		),
		"description" => __("Set to 'Yes' if you want to show 'Name' field in guest booking form.", "timetable"),
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("Guest name field required", "timetable"),
		"param_name" => "guest_name_field_required",
		"value" => array(
			__("Yes", "timetable") => "yes",
			__("No", "timetable") => "no",
		),
		"dependency" => array(
			"element" => "allow_guest_booking",
			"value" => array("yes"),
		),
		"description" => __("Set to 'Yes' if the 'Name' field should be required.", "timetable"),
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("Show guest phone field", "timetable"),
		"param_name" => "show_guest_phone_field",
		"value" => array(
			__("No", "timetable") => "no",
			__("Yes", "timetable") => "yes",
		),
		"dependency" => array(
			"element" => "allow_guest_booking",
			"value" => array("yes"),
		),
		"description" => __("Set to 'Yes' if you want to show 'Phone' field in guest booking form.", "timetable"),
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("Guest phone field required", "timetable"),
		"param_name" => "guest_phone_field_required",
		"value" => array(
			__("No", "timetable") => "no",
			__("Yes", "timetable") => "yes",
		),
		"dependency" => array(
			"element" => "allow_guest_booking",
			"value" => array("yes"),
		),
		"description" => __("Set to 'Yes' if the 'Phone' field should be required.", "timetable"),
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("Show guest message field", "timetable"),
		"param_name" => "show_guest_message_field",
		"value" => array(
			__("No", "timetable") => "no",
			__("Yes", "timetable") => "yes",
		),
		"dependency" => array(
			"element" => "allow_guest_booking",
			"value" => array("yes"),
		),
		"description" => __("Set to 'Yes' if you want to show 'Message' field in guest booking form.", "timetable"),
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("Guest message field required", "timetable"),
		"param_name" => "guest_message_field_required",
		"value" => array(
			__("No", "timetable") => "no",
			__("Yes", "timetable") => "yes",
		),
		"dependency" => array(
			"element" => "allow_guest_booking",
			"value" => array("yes"),
		),
		"description" => __("Set to 'Yes' if the 'Message' field should be required.", "timetable"),
	),
	array(
		"type" => "textfield",
		"class" => "",
		"heading" => __("Booking label", "timetable"),
		"param_name" => "booking_label",
		"value" => __("Book now", "timetable"),
	),
	array(
		"type" => "textfield",
		"class" => "",
		"heading" => __("Booked label", "timetable"),
		"param_name" => "booked_label",
		"value" => __("Booked", "timetable"),
	),
	array(
		"type" => "textfield",
		"class" => "",
		"heading" => __("Unavailable label", "timetable"),
		"param_name" => "unavailable_label",
		"value" => __("Unavailable", "timetable"),
	),
	array(
		"type" => "textfield",
		"class" => "",
		"heading" => __("Popup booking label", "timetable"),
		"param_name" => "booking_popup_label",
		"value" => __("Book now", "timetable"),
	),
	array(
		"type" => "textfield",
		"class" => "",
		"heading" => __("Popup login label", "timetable"),
		"param_name" => "login_popup_label",
		"value" => __("Log in", "timetable"),
	),
	array(
		"type" => "textfield",
		"class" => "",
		"heading" => __("Popup cancel label", "timetable"),
		"param_name" => "cancel_popup_label",
		"value" => __("Cancel", "timetable"),
	),
	array(
		"type" => "textfield",
		"class" => "",
		"heading" => __("Popup continue label", "timetable"),
		"param_name" => "continue_popup_label",
		"value" => __("Continue", "timetable"),
	),
	array(
		"type" => "dropdown",
		"class" => "",
		"heading" => __("Terms and conditions checkbox", "timetable"),
		"param_name" => "terms_checkbox",
		"value" => array(
			__("No", "timetable") => "no",
			__("Yes", "timetable") => "yes",
		),
		"description" => __("Set to 'Yes' if you want to display 'Terms and conditions' checkbox.", "timetable"),
	),
	array(
		"type" => "textfield",
		"class" => "",
		"heading" => __("Terms and conditions message", "timetable"),
		"param_name" => "terms_message",
		"value" => __("Please accept terms and conditions", "timetable"),
		"description" => __("Specify text for 'Terms and conditions' checkbox.", "timetable"),
	),
	array(
		"type" => "textarea",
		"class" => "",
		"heading" => __("Booking pop-up message", "timetable"),
		"param_name" => "booking_popup_message",
		"value" => BOOKING_POPUP_MESSAGE,
		"description" => __("Specify text that will appear in pop-up window. Available placeholders: {event_title} {column_title} {event_start} {event_end} {event_description_1} {event_description_2} {user_name} {user_email} {tt_btn_book} {tt_btn_cancel} {tt_btn_continue}", 'timetable'),
	),
	array(
		"type" => "textarea",
		"class" => "",
		"heading" => __("Booking pop-up thank you message", "timetable"),
		"param_name" => "booking_popup_thank_you_message",
		"value" => BOOKING_POPUP_THANK_YOU_MESSAGE,
		"description" => __("Specify text that will appear in pop-up window. Available placeholders: {event_title} {column_title} {event_start} {event_end} {event_description_1} {event_description_2} {user_name} {user_email} {tt_btn_continue}", 'timetable'),
	),
	array(
		"type" => "textarea",
		"class" => "",
		"heading" => __("Custom CSS", "timetable"),
		"param_name" => "custom_css",
		"value" => "",
	),
);
